spring:
  application:
    name: JWT Token Auth
  datasource:
    url: jdbc:postgresql://localhost:5432/db?createDatabaseIfNotExist=true
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: com.example.jwt.token.auth.util.ImprovedPostgreSqlDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

server:
  port: 8080

logging:
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n'

---

spring:
  profiles: docker
  application:
    name: JWT Token Auth
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: com.example.jwt.token.auth.util.ImprovedPostgreSqlDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

server:
  port: 8080

logging:
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n'
